baseurl = "http://thomshutt.github.io"
languageCode = "en-gb"
title = "Thom Shutt"
theme = "purehugo"
Paginate = 20
disqusShortname = "thomshutt"

[params]
  twitterName = "thomshutt"
  githubName  = "thomshutt"
